services:
  awg-test:
    image: registry.eterline.ru/amnezia:latest
    container_name: awg-test
    hostname: awg-test
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - "./scripts:/scripts:rw"
    entrypoint: ["amneziawg-go", "-f", "awg0"]
    tty: true
    stdin_open: true
    restart: "no"
