version: "3"

includes:

  amnezia:
    taskfile: "./amnezia/Taskfile.yaml"
    dir: "./amnezia"

  olcrtc:
    taskfile: "./olcrtc/Taskfile.yaml"
    dir: "./olcrtc"

  singbox:
    taskfile: "./singbox/Taskfile.yaml"
    dir: "./singbox"

# ============== Tasks ==============
tasks:

  export:
    cmds:
      - rm -rf ./images || true
      - mkdir -p ./images
      - |
        docker image ls --format '{{`{{.Repository}}:{{.Tag}}`}}' | grep -v '<none>' \
          | while read -r image; do
              name=$(echo "$image" | tr '/:' '_')
              docker save "$image" -o "./images/${name}.tar"
            done

  push-images:
    vars:
      PREFIX: '{{.PREFIX | default ""}}'
      REGISTRY: '{{.REGISTRY | default "registry.eterline.ru"}}'
    cmds:
      - |
        set -e \

        docker image ls --format '{{`{{.Repository}}:{{.Tag}}`}}' \
          | grep '^{{.PREFIX}}' \
          | while read -r image; do
              target="{{.REGISTRY}}/${image#{{.PREFIX}}}"
              echo "Pushing $image -> $target"
              docker tag "$image" "$target"
              docker push "$target"
            done